### ISSUE TITLE
TWarden-1.1.0 crashes on creating a new world

### ISSUE THREAD

**Issue by padgg** [MasterAbdoTGM50/ThaumicWarden#10]
at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:275)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1558)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 22
    Entity Name: allens
    Entity's Exact location: 1030.50, 4.00, -316.50
    Entity's Block location: World: (1030,4,-317), Chunk: (at 6,0,3 in 64,-20; contains blocks 1024,0,-320 to 1039,255,-305), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@65092771
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 131233080 bytes (125 MB) / 316805120 bytes (302 MB) up to 1038876672 bytes (990 MB)
    JVM Flags: 2 total; -Xincgc -Xmx1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 6 mods loaded, 6 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.25.1208} [Forge Mod Loader](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1208} [Minecraft Forge](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.7} [Baubles](Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TWarden{1.1.0} [Thaumic Warden](TWarden-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['allens'/22, l='新的世界', x=1030.50, y=4.00, z=-316.50]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MasterAbdoTGM50** [comment]
Can you please give more details? I take it this is a crash on startup? Are you using the latest forge btw?

**Comment by MasterAbdoTGM50** [comment]
Did you use the Purity Focus?

**Comment by padgg** [comment]
It crashs on build a new world,not crash on start up .my forge version is 10.13.0.1208,i didn't use Purity Focus.

**Comment by MasterAbdoTGM50** [comment]
Alright, send me a modlist and I will look into it once Im back home

**Comment by padgg** [comment]
MOD list
-mcp-9.05
-FML-7.10.25.1208
-Forge-10.13.0.1208
-Baubles-1.7.10-1.0.1.7
-Thaumcraft-1.7.10-4.2.0.1
-TWarden-1.1.0

**Comment by MasterAbdoTGM50** [comment]
Ok I reduplicated the issue and I think I know the cause. Will fix it right away. Thanks my good sir.
